from pathlib import Path

from django.conf import settings
from django.utils import timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas


PAGE_WIDTH, PAGE_HEIGHT = A4

TEAL = colors.HexColor("#0F766E")
DARK = colors.HexColor("#111827")
GRAY = colors.HexColor("#6B7280")
LIGHT_GRAY = colors.HexColor("#E5E7EB")
VERY_LIGHT = colors.HexColor("#F8FAFC")
TABLE_HEADER = colors.HexColor("#ECFDF5")


PDF_TEXTS = {
    "uz": {
        "clinic": "VETCLINIC",
        "subtitle": "Hayvon sog‘lig‘i bo‘yicha yakuniy ko‘rik varaqasi",
        "document_no": "Hujjat №",
        "date": "Sana",
        "request_no": "Ariza №",
        "status": "Holat",
        "completed": "Yakunlandi",
        "client_info": "Mijoz ma’lumotlari",
        "pet_info": "Hayvon ma’lumotlari",
        "full_name": "F.I.Sh.",
        "phone": "Telefon",
        "telegram_id": "Telegram ID",
        "address": "Manzil",
        "pet_id": "Hayvon ID",
        "pet_name": "Nomi",
        "pet_type": "Turi",
        "pet_age": "Yoshi",
        "checkup_info": "Ko‘rik ma’lumotlari",
        "veterinarian": "Veterinar",
        "checkup_date": "Ko‘rik sanasi",
        "complaint": "Shikoyat",
        "general_status": "Umumiy holat",
        "diagnosis": "Tashxis",
        "treatment": "Davolash va tavsiyalar",
        "extra_recommendation": "Qo‘shimcha tavsiyalar",
        "number": "№",
        "procedure": "Muolaja / dori",
        "amount": "Miqdor",
        "duration": "Muddat",
        "signature": "Veterinar imzosi",
        "stamp": "Klinika muhri",
        "footer": "PDF VetClinic tizimi orqali yaratildi",
        "no_info": "-",
    },
    "ru": {
        "clinic": "VETCLINIC",
        "subtitle": "Итоговый лист осмотра здоровья животного",
        "document_no": "Документ №",
        "date": "Дата",
        "request_no": "Заявка №",
        "status": "Статус",
        "completed": "Завершено",
        "client_info": "Данные клиента",
        "pet_info": "Данные животного",
        "full_name": "Ф.И.О.",
        "phone": "Телефон",
        "telegram_id": "Telegram ID",
        "address": "Адрес",
        "pet_id": "ID животного",
        "pet_name": "Имя",
        "pet_type": "Тип",
        "pet_age": "Возраст",
        "checkup_info": "Данные осмотра",
        "veterinarian": "Ветеринар",
        "checkup_date": "Дата осмотра",
        "complaint": "Жалоба",
        "general_status": "Общее состояние",
        "diagnosis": "Диагноз",
        "treatment": "Лечение и рекомендации",
        "extra_recommendation": "Дополнительные рекомендации",
        "number": "№",
        "procedure": "Процедура / препарат",
        "amount": "Доза",
        "duration": "Срок",
        "signature": "Подпись ветеринара",
        "stamp": "Печать клиники",
        "footer": "PDF создан системой VetClinic",
        "no_info": "-",
    },
    "en": {
        "clinic": "VETCLINIC",
        "subtitle": "Final animal health checkup report",
        "document_no": "Document No",
        "date": "Date",
        "request_no": "Request No",
        "status": "Status",
        "completed": "Completed",
        "client_info": "Client information",
        "pet_info": "Pet information",
        "full_name": "Full name",
        "phone": "Phone",
        "telegram_id": "Telegram ID",
        "address": "Address",
        "pet_id": "Pet ID",
        "pet_name": "Name",
        "pet_type": "Type",
        "pet_age": "Age",
        "checkup_info": "Checkup information",
        "veterinarian": "Veterinarian",
        "checkup_date": "Checkup date",
        "complaint": "Complaint",
        "general_status": "General condition",
        "diagnosis": "Diagnosis",
        "treatment": "Treatment and recommendations",
        "extra_recommendation": "Additional recommendations",
        "number": "No",
        "procedure": "Procedure / medicine",
        "amount": "Amount",
        "duration": "Duration",
        "signature": "Veterinarian signature",
        "stamp": "Clinic stamp",
        "footer": "PDF generated by VetClinic system",
        "no_info": "-",
    },
}


def normalize_lang(lang):
    lang = (lang or "uz").lower().strip()
    return lang if lang in PDF_TEXTS else "uz"


def safe_text(value, default="-"):
    if value is None:
        return default

    value = str(value).strip()
    return value if value else default


def compact_text(value, default="-"):
    return " ".join(safe_text(value, default).split())


def clean_complaint_for_pdf(value):
    """
    PDF ichida bot texnik matnlari va eski ko‘riklar tarixi chiqmasligi uchun.
    """
    text = compact_text(value, "")

    if not text:
        return "-"

    # Eski ko‘rik tarixi boshlansa, shu joydan kesamiz
    cut_markers = [
        "Veterinar ko‘rigi yakunlandi:",
        "Veterinar ko'rigi yakunlandi:",
        "Ko‘rik kodi:",
        "Ko'rik kodi:",
        "Umumiy xulosa:",
        "Tavsiya:",
        "Qo‘shimcha izoh:",
        "Qo'shimcha izoh:",
    ]

    for marker in cut_markers:
        index = text.find(marker)
        if index != -1:
            text = text[:index].strip()

    # Telegram bot texnik iboralarini olib tashlaymiz
    remove_phrases = [
        "Telegram bot orqali yuborilgan ariza",
        "Telegram bot orqali xabar yuborildi.",
        "Telegram bot orqali xabar yuborildi",
        "Telegram orqali joylashuv yuborildi",
        "Xizmat turi:",
        "Muammo tavsifi / izoh:",
        "Manzil:",
        "Xavf turi:",
    ]

    for phrase in remove_phrases:
        text = text.replace(phrase, " ")

    text = " ".join(text.split(" ."))
    text = " ".join(text.split())

    # Agar baribir uzun bo‘lsa, qisqartiramiz
    if not text:
        return "-"

    return text[:180].rstrip() + "..." if len(text) > 180 else text


def truncate_to_width(pdf, text, max_width, font_name, font_size):
    text = safe_text(text)

    if pdf.stringWidth(text, font_name, font_size) <= max_width:
        return text

    result = ""

    for char in text:
        test = result + char

        if pdf.stringWidth(test + "...", font_name, font_size) > max_width:
            break

        result = test

    return result.rstrip() + "..." if result else "..."


def get_patient(visit):
    return (
        getattr(visit, "new_patient", None)
        or getattr(visit, "patient", None)
        or getattr(visit, "application", None)
    )


def get_pet(visit, patient=None):
    return (
        getattr(visit, "pet", None)
        or getattr(patient, "pet", None)
        or None
    )


def get_doctor_name(visit):
    doctor = getattr(visit, "doctor", None)

    if not doctor:
        return "-"

    try:
        full_name = doctor.get_full_name()

        if full_name:
            return full_name
    except Exception:
        pass

    return safe_text(getattr(doctor, "username", None), "-")


def get_pet_type(pet, patient=None):
    if pet and hasattr(pet, "get_animal_type_display"):
        try:
            return safe_text(pet.get_animal_type_display())
        except Exception:
            pass

    if pet:
        return safe_text(getattr(pet, "animal_type", None))

    if patient and hasattr(patient, "get_animal_type_display"):
        try:
            return safe_text(patient.get_animal_type_display())
        except Exception:
            pass

    return safe_text(getattr(patient, "animal_type", None), "-")


def get_visit_date(visit):
    value = getattr(visit, "created_at", None) or timezone.now()

    try:
        return timezone.localtime(value).strftime("%d.%m.%Y %H:%M")
    except Exception:
        return safe_text(value)


def register_font():
    font_paths = [
        Path(settings.BASE_DIR) / "static" / "fonts" / "DejaVuSans.ttf",
        Path(settings.BASE_DIR) / "fonts" / "DejaVuSans.ttf",
        Path("C:/Windows/Fonts/arial.ttf"),
        Path("C:/Windows/Fonts/Arial.ttf"),
        Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
    ]

    for font_path in font_paths:
        if font_path.exists():
            pdfmetrics.registerFont(TTFont("VetFont", str(font_path)))
            return "VetFont"

    return "Helvetica"


def wrap_text(pdf, text, max_width, font_name, font_size, max_lines=None):
    text = compact_text(text)
    words = text.split()
    lines = []
    current = ""

    for word in words:
        test = f"{current} {word}".strip()

        if pdf.stringWidth(test, font_name, font_size) <= max_width:
            current = test
        else:
            if current:
                lines.append(current)

            current = word

        if max_lines and len(lines) >= max_lines:
            break

    if current and (not max_lines or len(lines) < max_lines):
        lines.append(current)

    if not lines:
        lines = ["-"]

    if max_lines and len(lines) > max_lines:
        lines = lines[:max_lines]

    if max_lines:
        original = " ".join(words)
        displayed = " ".join(lines)

        if len(displayed) < len(original):
            last = lines[-1]

            while last and pdf.stringWidth(last + "...", font_name, font_size) > max_width:
                last = last[:-1]

            lines[-1] = last.rstrip() + "..."

    return lines


def draw_card(pdf, x, y, w, h):
    pdf.setFillColor(colors.white)
    pdf.setStrokeColor(LIGHT_GRAY)
    pdf.setLineWidth(0.9)
    pdf.roundRect(x, y, w, h, 8, stroke=1, fill=1)


def draw_section_title(pdf, title, x, y, font_name):
    pdf.setFillColor(TEAL)
    pdf.setFont(font_name, 11)
    pdf.drawString(x, y, title)


def draw_label_value(pdf, label, value, x, y, label_width, font_name, font_size=8.5, max_value_width=None):
    pdf.setFont(font_name, font_size)
    pdf.setFillColor(GRAY)
    pdf.drawString(x, y, f"{label}:")

    value_text = safe_text(value)

    if max_value_width:
        value_text = truncate_to_width(pdf, value_text, max_value_width, font_name, font_size)

    pdf.setFillColor(DARK)
    pdf.drawString(x + label_width, y, value_text)


def draw_wrapped_text(pdf, text, x, y, max_width, font_name, font_size=8.5, line_height=12, max_lines=None):
    pdf.setFont(font_name, font_size)
    pdf.setFillColor(DARK)

    lines = wrap_text(pdf, text, max_width, font_name, font_size, max_lines=max_lines)

    for line in lines:
        pdf.drawString(x, y, line)
        y -= line_height

    return y


def draw_table(pdf, x, y, w, rows, texts, font_name):
    col_widths = [
        w * 0.09,
        w * 0.49,
        w * 0.20,
        w * 0.22,
    ]

    header_h = 20
    row_h = 20

    headers = [
        texts["number"],
        texts["procedure"],
        texts["amount"],
        texts["duration"],
    ]

    pdf.setFillColor(TABLE_HEADER)
    pdf.setStrokeColor(LIGHT_GRAY)
    pdf.rect(x, y - header_h, w, header_h, stroke=1, fill=1)

    pdf.setFont(font_name, 8)
    pdf.setFillColor(TEAL)

    current_x = x

    for index, header in enumerate(headers):
        header_text = truncate_to_width(pdf, header, col_widths[index] - 8, font_name, 8)
        pdf.drawString(current_x + 5, y - 13, header_text)
        current_x += col_widths[index]

    table_y = y - header_h

    for row_index, row in enumerate(rows):
        row_top = table_y - row_index * row_h

        pdf.setFillColor(colors.white)
        pdf.setStrokeColor(LIGHT_GRAY)
        pdf.rect(x, row_top - row_h, w, row_h, stroke=1, fill=1)

        current_x = x

        for col_index, cell in enumerate(row):
            cell_text = safe_text(cell)
            pdf.setFillColor(DARK)
            pdf.setFont(font_name, 8)

            if col_index == 0:
                pdf.drawCentredString(current_x + col_widths[col_index] / 2, row_top - 13, cell_text)
            else:
                max_text_width = col_widths[col_index] - 8
                cell_text = truncate_to_width(pdf, cell_text, max_text_width, font_name, 8)
                pdf.drawString(current_x + 5, row_top - 13, cell_text)

            current_x += col_widths[col_index]

    total_h = header_h + len(rows) * row_h

    current_x = x

    for col_w in col_widths[:-1]:
        current_x += col_w
        pdf.setStrokeColor(LIGHT_GRAY)
        pdf.line(current_x, y, current_x, y - total_h)

    return y - total_h


def get_treatment_rows(visit):
    treatment = compact_text(getattr(visit, "treatment", None), "")

    if not treatment:
        return [["1", "-", "-", "-"]]

    lines = [line.strip() for line in treatment.splitlines() if line.strip()]

    if not lines:
        lines = [treatment]

    rows = []

    for index, line in enumerate(lines[:3], start=1):
        rows.append([str(index), line, "-", "-"])

    return rows or [["1", "-", "-", "-"]]


def draw_stamp(pdf, x, y, font_name):
    pdf.setStrokeColor(TEAL)
    pdf.setLineWidth(1)
    pdf.circle(x, y, 22, stroke=1, fill=0)
    pdf.circle(x, y, 16, stroke=1, fill=0)

    pdf.setFont(font_name, 7)
    pdf.setFillColor(TEAL)
    pdf.drawCentredString(x, y + 7, "VETCLINIC")
    pdf.drawCentredString(x, y - 8, "STAMP")


def get_report_path(visit):
    media_root = Path(getattr(settings, "MEDIA_ROOT", None) or (Path(settings.BASE_DIR) / "media"))
    reports_dir = media_root / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)

    visit_code = safe_text(getattr(visit, "visit_code", None), "")
    visit_id = safe_text(getattr(visit, "id", None), "unknown")

    if visit_code and visit_code != "-":
        file_name = f"visit_{visit_code}.pdf"
    else:
        file_name = f"visit_{visit_id}.pdf"

    return reports_dir / file_name


def generate_visit_pdf(visit, lang="uz"):
    lang = normalize_lang(lang)
    texts = PDF_TEXTS[lang]
    font_name = register_font()

    patient = get_patient(visit)
    pet = get_pet(visit, patient)

    output_path = get_report_path(visit)

    pdf = canvas.Canvas(str(output_path), pagesize=A4)
    width, height = A4

    margin = 38
    content_w = width - margin * 2

    pdf.setFillColor(VERY_LIGHT)
    pdf.rect(0, 0, width, height, stroke=0, fill=1)

    y = height - 46

    pdf.setFillColor(TEAL)
    pdf.setFont(font_name, 24)
    pdf.drawString(margin, y, texts["clinic"])

    pdf.setFillColor(GRAY)
    pdf.setFont(font_name, 9.5)
    pdf.drawString(margin, y - 17, texts["subtitle"])

    visit_code = safe_text(getattr(visit, "visit_code", None), "-")
    patient_code = safe_text(getattr(patient, "patient_code", None), "-")
    date_text = timezone.localdate().strftime("%d.%m.%Y")

    meta_x = width - margin - 145
    meta_y = y + 2

    meta_rows = [
        (texts["document_no"], visit_code),
        (texts["date"], date_text),
        (texts["request_no"], patient_code),
        (texts["status"], texts["completed"]),
    ]

    pdf.setFont(font_name, 8.5)

    for label, value in meta_rows:
        pdf.setFillColor(GRAY)
        pdf.drawString(meta_x, meta_y, f"{label}:")
        pdf.setFillColor(DARK)
        pdf.drawString(meta_x + 70, meta_y, safe_text(value))
        meta_y -= 13

    pdf.setStrokeColor(TEAL)
    pdf.setLineWidth(1.2)
    pdf.line(margin, y - 48, width - margin, y - 48)

    card_gap = 12
    card_w = (content_w - card_gap) / 2
    card_h = 91
    card_y = y - 150

    # Client card
    draw_card(pdf, margin, card_y, card_w, card_h)
    draw_section_title(pdf, texts["client_info"], margin + 14, card_y + card_h - 22, font_name)

    client_y = card_y + card_h - 42
    client_value_w = card_w - 100

    draw_label_value(pdf, texts["full_name"], getattr(patient, "full_name", "-"), margin + 14, client_y, 70, font_name, max_value_width=client_value_w)
    draw_label_value(pdf, texts["phone"], getattr(patient, "phone", "-"), margin + 14, client_y - 15, 70, font_name, max_value_width=client_value_w)
    draw_label_value(pdf, texts["telegram_id"], getattr(patient, "telegram_id", "-"), margin + 14, client_y - 30, 70, font_name, max_value_width=client_value_w)
    draw_label_value(pdf, texts["address"], getattr(patient, "address_text", "-"), margin + 14, client_y - 45, 70, font_name, max_value_width=client_value_w)

    # Pet card
    right_x = margin + card_w + card_gap

    draw_card(pdf, right_x, card_y, card_w, card_h)
    draw_section_title(pdf, texts["pet_info"], right_x + 14, card_y + card_h - 22, font_name)

    pet_code = safe_text(getattr(pet, "pet_code", None), "-")
    pet_name = safe_text(getattr(pet, "name", None), getattr(patient, "animal_name", "-"))
    pet_type = get_pet_type(pet, patient)

    pet_y = card_y + card_h - 42
    pet_value_w = card_w - 100

    draw_label_value(pdf, texts["pet_id"], pet_code, right_x + 14, pet_y, 70, font_name, max_value_width=pet_value_w)
    draw_label_value(pdf, texts["pet_name"], pet_name, right_x + 14, pet_y - 15, 70, font_name, max_value_width=pet_value_w)
    draw_label_value(pdf, texts["pet_type"], pet_type, right_x + 14, pet_y - 30, 70, font_name, max_value_width=pet_value_w)
    draw_label_value(pdf, texts["pet_age"], "-", right_x + 14, pet_y - 45, 70, font_name, max_value_width=pet_value_w)

    # Checkup info
    y2 = card_y - 16
    check_h = 126

    draw_card(pdf, margin, y2 - check_h, content_w, check_h)
    draw_section_title(pdf, texts["checkup_info"], margin + 14, y2 - 22, font_name)

    row_y = y2 - 42
    label_x = margin + 14
    value_x = label_x + 90
    value_w = content_w - 28 - 90

    draw_label_value(pdf, texts["veterinarian"], get_doctor_name(visit), label_x, row_y, 90, font_name, max_value_width=value_w)
    draw_label_value(pdf, texts["checkup_date"], get_visit_date(visit), label_x, row_y - 15, 90, font_name, max_value_width=value_w)

    pdf.setFont(font_name, 8.5)
    pdf.setFillColor(GRAY)
    pdf.drawString(label_x, row_y - 30, f"{texts['complaint']}:")

    complaint = clean_complaint_for_pdf(getattr(visit, "complaint", None))
    complaint_lines = wrap_text(pdf, complaint, value_w, font_name, 8.5, max_lines=3)

    pdf.setFont(font_name, 8.5)
    pdf.setFillColor(DARK)

    complaint_y = row_y - 30

    for line in complaint_lines:
        pdf.drawString(value_x, complaint_y, line)
        complaint_y -= 11

    status_y = y2 - check_h + 16
    draw_label_value(pdf, texts["general_status"], texts["completed"], label_x, status_y, 90, font_name, max_value_width=value_w)

    # Diagnosis
    diag_y = y2 - check_h - 16
    diag_h = 78

    draw_card(pdf, margin, diag_y - diag_h, content_w, diag_h)
    draw_section_title(pdf, texts["diagnosis"], margin + 14, diag_y - 22, font_name)

    diagnosis = compact_text(getattr(visit, "diagnosis", None), texts["no_info"])

    draw_wrapped_text(
        pdf,
        diagnosis,
        margin + 14,
        diag_y - 42,
        content_w - 28,
        font_name,
        8.5,
        12,
        max_lines=3,
    )

    # Treatment
    treat_y = diag_y - diag_h - 16
    treat_h = 104

    draw_card(pdf, margin, treat_y - treat_h, content_w, treat_h)
    draw_section_title(pdf, texts["treatment"], margin + 14, treat_y - 22, font_name)

    treatment_rows = get_treatment_rows(visit)
    draw_table(pdf, margin + 14, treat_y - 38, content_w - 28, treatment_rows, texts, font_name)

    # Extra recommendation
    rec_y = treat_y - treat_h - 16
    rec_h = 70

    draw_card(pdf, margin, rec_y - rec_h, content_w, rec_h)
    draw_section_title(pdf, texts["extra_recommendation"], margin + 14, rec_y - 22, font_name)

    extra = compact_text(getattr(visit, "message", None), texts["no_info"])

    draw_wrapped_text(
        pdf,
        extra,
        margin + 14,
        rec_y - 42,
        content_w - 28,
        font_name,
        8.5,
        12,
        max_lines=2,
    )

    # Footer
    footer_y = 65

    pdf.setFillColor(DARK)
    pdf.setFont(font_name, 9)
    pdf.drawString(margin + 12, footer_y + 20, f"{texts['signature']}: __________________")

    pdf.drawString(width - margin - 160, footer_y + 20, f"{texts['stamp']}:")
    draw_stamp(pdf, width - margin - 43, footer_y + 25, font_name)

    pdf.setStrokeColor(TEAL)
    pdf.setLineWidth(1)
    pdf.line(margin, 32, width - margin, 32)

    pdf.setFillColor(GRAY)
    pdf.setFont(font_name, 8)
    pdf.drawCentredString(width / 2, 19, texts["footer"])

    pdf.save()

    return str(output_path)