# Generated by Django 6.0.4 on 2026-04-26 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Egasi kodi')),
                ('full_name', models.CharField(max_length=255, verbose_name='Egasi F.I.Sh')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ro‘yxatga olingan vaqt')),
            ],
            options={
                'verbose_name': 'Hayvon egasi',
                'verbose_name_plural': 'Hayvon egalari',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Hayvon kodi')),
                ('name', models.CharField(max_length=100, verbose_name='Hayvon nomi')),
                ('animal_type', models.CharField(choices=[('dog', 'It'), ('cat', 'Mushuk'), ('cow', 'Sigir'), ('horse', 'Ot'), ('sheep', 'Qo‘y'), ('goat', 'Echki'), ('bird', 'Qush'), ('other', 'Boshqa')], max_length=50, verbose_name='Hayvon turi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ro‘yxatga olingan vaqt')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.owner', verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Hayvon',
                'verbose_name_plural': 'Hayvonlar',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Ko‘rik raqami')),
                ('complaint', models.TextField(blank=True, null=True, verbose_name='Shikoyat')),
                ('diagnosis', models.TextField(verbose_name='Tashxis')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='Davolash')),
                ('next_visit', models.DateTimeField(blank=True, null=True, verbose_name='Qayta kelish sanasi')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Xabar matni')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Yuborildimi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ko‘rik vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Mas’ul doktor')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.pet', verbose_name='Hayvon')),
            ],
            options={
                'verbose_name': 'Ko‘rik',
                'verbose_name_plural': 'Ko‘riklar',
            },
        ),
    ]
