# Generated by Django 6.0.4 on 2026-04-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyVisit',
            fields=[
            ],
            options={
                'verbose_name': 'Mening bemorim',
                'verbose_name_plural': 'Mening bemorlarim',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('patients.visit',),
        ),
    ]
