# Generated by Django 6.0.4 on 2026-04-26 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_myvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mutaxassisligi')),
                ('experience', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ish tajribasi')),
                ('resume', models.TextField(blank=True, null=True, verbose_name='Rezyume')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Doktor akkaunti')),
            ],
            options={
                'verbose_name': 'Veterinar doktor',
                'verbose_name_plural': 'Veterinar doktorlar',
            },
        ),
        migrations.CreateModel(
            name='NewPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Bemor kodi')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='new', max_length=20, verbose_name='Holati')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kelgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('selected_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.doctorprofile', verbose_name='Tanlangan doktor')),
            ],
            options={
                'verbose_name': 'Yangi bemor',
                'verbose_name_plural': 'Yangi bemorlar',
            },
        ),
    ]
