# Generated by Django 6.0.4 on 2026-04-26 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_doctorprofile_newpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='new_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.newpatient', verbose_name='Yangi bemor'),
        ),
    ]
