# Generated by Django 6.0.4 on 2026-04-26 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_visit_new_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpatient',
            name='animal_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hayvon nomi'),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='animal_type',
            field=models.CharField(blank=True, choices=[('dog', 'It'), ('cat', 'Mushuk'), ('cow', 'Sigir'), ('horse', 'Ot'), ('sheep', 'Qo‘y'), ('goat', 'Echki'), ('bird', 'Qush'), ('other', 'Boshqa')], max_length=50, null=True, verbose_name='Hayvon turi'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.pet', verbose_name='Hayvon'),
        ),
    ]
