# Generated by Django 6.0.4 on 2026-04-29 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_newpatient_animal_name_newpatient_animal_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="newpatient",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Yangi ariza"),
                    ("assigned_to_vet", "Veterinarga yuborildi"),
                    ("sent_to_lab", "Laboratoriyaga yuborildi"),
                    ("sent_to_diagnostic", "Diagnostikaga yuborildi"),
                    ("returned_to_vet", "Veterinarga qaytdi"),
                    ("completed", "Yakunlandi"),
                    ("cancelled", "Bekor qilindi"),
                    ("accepted", "Qabul qilindi"),
                    ("rejected", "Rad etildi"),
                ],
                default="new",
                max_length=20,
                verbose_name="Holati",
            ),
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_name",
                    models.CharField(max_length=255, verbose_name="Analiz nomi"),
                ),
                (
                    "result",
                    models.TextField(
                        blank=True, null=True, verbose_name="Analiz natijasi"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Izoh"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Kutilmoqda"),
                            ("done", "Tayyor"),
                            ("sent_to_diagnostic", "Diagnostikaga yuborildi"),
                        ],
                        default="waiting",
                        max_length=30,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "lab_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_results_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Laboratoriya xodimi",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_results",
                        to="patients.newpatient",
                        verbose_name="Bemor",
                    ),
                ),
                (
                    "veterinarian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yuborgan veterinar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Laboratoriya natijasi",
                "verbose_name_plural": "Laboratoriya natijalari",
            },
        ),
        migrations.CreateModel(
            name="DiagnosticResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conclusion", models.TextField(verbose_name="Diagnostik xulosa")),
                (
                    "recommendation",
                    models.TextField(blank=True, null=True, verbose_name="Tavsiya"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Kutilmoqda"),
                            ("done", "Tayyor"),
                            ("returned_to_vet", "Veterinarga qaytarildi"),
                        ],
                        default="waiting",
                        max_length=30,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "diagnostic_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnostic_results_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diagnostika xodimi",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostic_results",
                        to="patients.newpatient",
                        verbose_name="Bemor",
                    ),
                ),
                (
                    "lab_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnostic_results",
                        to="patients.labresult",
                        verbose_name="Laboratoriya natijasi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnostika natijasi",
                "verbose_name_plural": "Diagnostika natijalari",
            },
        ),
    ]
