# Generated by Django 6.0.4 on 2026-04-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_alter_newpatient_status_labresult_diagnosticresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newpatient",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Yangi ariza"),
                    ("assigned_to_vet", "Veterinarga yuborildi"),
                    ("sent_to_lab", "Laboratoriyaga yuborildi"),
                    ("sent_to_diagnostic", "Diagnostikaga yuborildi"),
                    ("returned_to_vet", "Veterinarga qaytdi"),
                    ("completed", "Yakunlandi"),
                    ("cancelled", "Bekor qilindi"),
                    ("accepted", "Qabul qilindi"),
                    ("rejected", "Rad etildi"),
                ],
                default="new",
                max_length=30,
                verbose_name="Holati",
            ),
        ),
    ]
