# Generated by Django 6.0.4 on 2026-04-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_alter_newpatient_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="labresult",
            name="lab_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Laboratoriya izohi"
            ),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Veterinar izohi"
            ),
        ),
    ]
