# Generated by Django 6.0.4 on 2026-04-29 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0008_labresult_lab_comment_alter_labresult_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticresult",
            name="is_lab_updated",
            field=models.BooleanField(
                default=False, verbose_name="Laboratoriya natijasi tahrirlanganmi?"
            ),
        ),
        migrations.AddField(
            model_name="diagnosticresult",
            name="lab_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Laboratoriya tahrirlagan vaqt"
            ),
        ),
        migrations.AddField(
            model_name="diagnosticresult",
            name="lab_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_update_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Laboratoriya tahrirlagan xodim",
            ),
        ),
    ]
