# Generated by Django 6.0.4 on 2026-05-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_diagnosticresult_is_lab_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='last_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Oxirgi kenglik'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='last_location_accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='Lokatsiya aniqligi'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='last_location_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi lokatsiya vaqti'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='last_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Oxirgi uzunlik'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='location_tracking_enabled',
            field=models.BooleanField(default=False, verbose_name='Geolokatsiya tracking yoqilganmi?'),
        ),
    ]
