# Generated by Django 6.0.4 on 2026-06-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_doctorprofile_last_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpatient',
            name='address_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik'),
        ),
        migrations.AddField(
            model_name='newpatient',
            name='service_type',
            field=models.CharField(choices=[('clinic', 'Klinikada davolash'), ('vet_call', 'Veterinar chaqirish'), ('danger', 'Xavfli holat')], db_index=True, default='clinic', max_length=20, verbose_name='Xizmat turi'),
        ),
        migrations.AlterField(
            model_name='newpatient',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi ariza'), ('assigned_to_vet', 'Veterinarga yuborildi'), ('en_route', 'Yo‘lda'), ('arrived', 'Yetib bordi'), ('sent_to_lab', 'Laboratoriyaga yuborildi'), ('sent_to_diagnostic', 'Diagnostikaga yuborildi'), ('returned_to_vet', 'Veterinarga qaytdi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='new', max_length=30, verbose_name='Holati'),
        ),
    ]
