# Generated by Django 6.0.4 on 2026-06-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_newpatient_address_text_newpatient_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='current_status',
            field=models.CharField(choices=[('free', 'Bo‘sh'), ('clinic', 'Klinikada'), ('on_call', 'Chaqiruvda'), ('busy', 'Band')], db_index=True, default='free', max_length=20, verbose_name='Joriy holat'),
        ),
    ]
