# Generated by Django 6.0.4 on 2026-06-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0012_doctorprofile_current_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="newpatient",
            name="language",
            field=models.CharField(
                default="uz", max_length=5, verbose_name="Foydalanuvchi tili"
            ),
        ),
    ]
