# Generated by Django 6.0.4 on 2026-06-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0013_newpatient_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newpatient",
            name="telegram_id",
            field=models.BigIntegerField(db_index=True, verbose_name="Telegram ID"),
        ),
    ]
