# Generated by Django 6.0.4 on 2026-06-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0014_alter_newpatient_telegram_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        db_index=True, unique=True, verbose_name="Telegram ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Ism"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Familiya"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="To‘liq ism"
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Telegram tili",
                    ),
                ),
                ("is_bot", models.BooleanField(default=False, verbose_name="Botmi?")),
                (
                    "start_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="/start bosgan soni"
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(auto_now=True, verbose_name="Oxirgi faollik"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Birinchi kirgan vaqt"
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram foydalanuvchi",
                "verbose_name_plural": "Telegram foydalanuvchilar",
                "ordering": ["-last_seen_at"],
            },
        ),
    ]
