# Generated by Django 6.0.4 on 2026-06-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0015_telegramuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="phone",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Telefon raqam"
            ),
        ),
    ]
